# Default values for chaos-engineering-service
# This is a YAML-formatted file.

# Controller configuration
controller:
  replicaCount: 1
  image:
    repository: chaos-engineering/controller
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# API server configuration
apiServer:
  replicaCount: 1
  image:
    repository: chaos-engineering/api-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chaos.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# RBAC configuration
rbac:
  create: true

# ServiceAccount configuration
serviceAccount:
  create: true
  name: "chaos-controller"
  annotations: {}
