apiVersion: chaos.engineering/v1alpha1
kind: ChaosExperiment
metadata:
  name: nginx-cpu-hog
  namespace: chaos-test
spec:
  target:
    apiVersion: v1
    kind: Pod
    name: nginx-test-0
    namespace: chaos-test
  experimentType: cpu-hog
  duration: "2m"
  parameters:
    cpuCores: "1"
