apiVersion: chaos.engineering/v1alpha1
kind: ChaosExperiment
metadata:
  name: nginx-pod-failure
  namespace: chaos-test
spec:
  target:
    apiVersion: v1
    kind: Pod
    name: nginx-test-0
    namespace: chaos-test
  experimentType: pod-failure
  duration: "30s"
  parameters: {}
