apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosexperiments.chaos.engineering
  labels:
    app.kubernetes.io/name: chaos-engineering
    app.kubernetes.io/part-of: chaos-engineering
spec:
  group: chaos.engineering
  names:
    kind: ChaosExperiment
    listKind: ChaosExperimentList
    plural: chaosexperiments
    singular: chaosexperiment
    shortNames:
      - cexp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                target:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                experimentType:
                  type: string
                  enum: ["pod-failure", "network-latency", "cpu-hog", "memory-hog"]
                duration:
                  type: string
                parameters:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                phase:
                  type: string
                startTime:
                  type: string
                  format: date-time
                endTime:
                  type: string
                  format: date-time
                message:
                  type: string
      additionalPrinterColumns:
      - name: Type
        type: string
        jsonPath: .spec.experimentType
      - name: Status
        type: string
        jsonPath: .status.phase
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
